import 'package:betterloop/constants/diet_icons.dart';
import 'package:betterloop/constants/health_icons.dart';
import 'package:betterloop/constants/negative_icons.dart';

import 'lifestyle_icons.dart';

import 'popular.dart';
import 'random_icons.dart';

const premiumicons = [
  PopularIcons.dogWithBeltWalkingWithAMan,
  LifeStyleIcons.vacuumCleaning,
  LifeStyleIcons.laundry,
  LifeStyleIcons.trashCollector,
  LifeStyleIcons.brushWithToothpaste,
  LifeStyleIcons.carWash,
  HealthIcons.bicycleSvgrepoCom,
  NegativeIcons.drinkCanSoda,
  NegativeIcons.cakeStop,
  DietIcons.breadSvgrepoCom,
  RandomIcons.airbudsCaseOpen,
  RandomIcons.alarmSleep,
  RandomIcons.americanFootballHelmet5,
  RandomIcons.bagHeartLove,
  RandomIcons.basketballGoal4,
  RandomIcons.beaver2,
  RandomIcons.bicycle4,
  RandomIcons.billiards1,
  RandomIcons.boneCrack,
  RandomIcons.bowlingPin1,
  RandomIcons.broom,
  RandomIcons.buildingConstructionSaw,
  RandomIcons.bunchOfBananas,
  RandomIcons.butterfly,
  RandomIcons.calendarDateHeart,
  RandomIcons.callChat,
  RandomIcons.cameraMinimalistic,
  RandomIcons.cap,
  RandomIcons.cart3,
  RandomIcons.cat3,
  RandomIcons.cheese,
  RandomIcons.chess9,
  RandomIcons.cloudyMoon,
  RandomIcons.comb,
  RandomIcons.confetti,
  RandomIcons.corePower,
  RandomIcons.dartArrow,
  RandomIcons.dinnerCandleWine,
  RandomIcons.dollHeartLove,
  RandomIcons.donut2,
  RandomIcons.drillGearTools,
  RandomIcons.dumbbell,
  RandomIcons.electricRefueling,
  RandomIcons.emojiFunnyCircle,
  RandomIcons.frog5,
  RandomIcons.gearToolsWrench,
  RandomIcons.giftBoxHeart,
  RandomIcons.golf1,
  RandomIcons.golf,
  RandomIcons.green,
  RandomIcons.hairDryer,
  RandomIcons.hamburgerPart21,
  RandomIcons.hanger2,
  RandomIcons.iceHockeyIllustration3,
  RandomIcons.keySquare2,
  RandomIcons.loveLetterMail,
  RandomIcons.maskSad,
  RandomIcons.moulding,
  RandomIcons.pallete2,
  RandomIcons.rose6,
  RandomIcons.route662,
  RandomIcons.seaBream,
  RandomIcons.seaTurtle,
  RandomIcons.seahorse,
  RandomIcons.slippers1,
  RandomIcons.smartphoneRotate2,
  RandomIcons.smartphoneVibration,
  RandomIcons.snail,
  RandomIcons.soccerBall,
  RandomIcons.sofa2,
  RandomIcons.starfish,
  RandomIcons.stretch,
  RandomIcons.surfing2,
  RandomIcons.tableTennis2,
  RandomIcons.takeawayCoffee2,
  RandomIcons.taxi4,
  RandomIcons.tea,
  RandomIcons.tennis2,
  RandomIcons.toothbrush,
  RandomIcons.train,
  RandomIcons.trump6,
  RandomIcons.umbrella,
  RandomIcons.washingMachine,
  RandomIcons.weight,
];
