import 'package:betterloop/constants/diet_icons.dart';
import 'package:betterloop/constants/health_icons.dart';
import 'package:betterloop/constants/negative_icons.dart';

import 'lifestyle_icons.dart';

import 'popular.dart';
import 'random_icons.dart';

const premiumicons = [
  PopularIcons.dog_with_belt_walking_with_a_man,
  LifeStyleIcons.vacuum_cleaning,
  LifeStyleIcons.laundry,
  LifeStyleIcons.trash_collector,
  LifeStyleIcons.brush_with_toothpaste,
  LifeStyleIcons.car_wash,
  HealthIcons.bicycle_svgrepo_com,
  NegativeIcons.drink_can_soda,
  NegativeIcons.cake_stop,
  DietIcons.bread_svgrepo_com,
  RandomIcons.airbuds_case_open,
  RandomIcons.alarm_sleep,
  RandomIcons.american_football_helmet_5,
  RandomIcons.bag_heart_love,
  RandomIcons.basketball_goal_4,
  RandomIcons.beaver_2,
  RandomIcons.bicycle_4,
  RandomIcons.billiards_1,
  RandomIcons.bone_crack,
  RandomIcons.bowling_pin_1,
  RandomIcons.broom,
  RandomIcons.building_construction_saw,
  RandomIcons.bunch_of_bananas,
  RandomIcons.butterfly,
  RandomIcons.calendar_date_heart,
  RandomIcons.call_chat,
  RandomIcons.camera_minimalistic,
  RandomIcons.cap,
  RandomIcons.cart_3,
  RandomIcons.cat_3,
  RandomIcons.cheese,
  RandomIcons.chess_9,
  RandomIcons.cloudy_moon,
  RandomIcons.comb,
  RandomIcons.confetti,
  RandomIcons.core_power,
  RandomIcons.dart_arrow,
  RandomIcons.dinner_candle_wine,
  RandomIcons.doll_heart_love,
  RandomIcons.donut_2,
  RandomIcons.drill_gear_tools,
  RandomIcons.dumbbell,
  RandomIcons.electric_refueling,
  RandomIcons.emoji_funny_circle,
  RandomIcons.frog_5,
  RandomIcons.gear_tools_wrench,
  RandomIcons.gift_box_heart,
  RandomIcons.golf_1,
  RandomIcons.golf,
  RandomIcons.green,
  RandomIcons.hair_dryer,
  RandomIcons.hamburger_part_2_1,
  RandomIcons.hanger_2,
  RandomIcons.ice_hockey_illustration_3,
  RandomIcons.key_square_2,
  RandomIcons.love_letter_mail,
  RandomIcons.mask_sad,
  RandomIcons.moulding,
  RandomIcons.pallete_2,
  RandomIcons.rose_6,
  RandomIcons.route_66_2,
  RandomIcons.sea_bream,
  RandomIcons.sea_turtle,
  RandomIcons.seahorse,
  RandomIcons.slippers1,
  RandomIcons.smartphone_rotate_2,
  RandomIcons.smartphone_vibration,
  RandomIcons.snail,
  RandomIcons.soccer_ball,
  RandomIcons.sofa_2,
  RandomIcons.starfish,
  RandomIcons.stretch,
  RandomIcons.surfing_2,
  RandomIcons.table_tennis_2,
  RandomIcons.takeaway_coffee_2,
  RandomIcons.taxi_4,
  RandomIcons.tea,
  RandomIcons.tennis_2,
  RandomIcons.toothbrush,
  RandomIcons.train,
  RandomIcons.trump_6,
  RandomIcons.umbrella,
  RandomIcons.washing_machine,
  RandomIcons.weight,
];
